name: Unicafe tests

on:
  push:
    branches: [main]

jobs:
  unicafe-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install app dependencies
        working-directory: part6/unicafe
        run: npm install

      - name: Install test dependencies
        working-directory: part6/unicafe-tests/unicafe-tests
        run: npm install

      - name: Install Playwright Chromium
        working-directory: part6/unicafe-tests/unicafe-tests
        run: npx playwright install --with-deps chromium

      - name: Run Unicafe tests
        working-directory: part6/unicafe-tests/unicafe-tests
        run: npm test